# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `code_ownership` gem.
# Please instead update this file by running `bin/tapioca gem code_ownership`.

# source://code_ownership-1.31.0/lib/code_ownership/cli.rb:7
module CodeOwnership
  extend ::CodeOwnership

  requires_ancestor { Kernel }

  # source://code_ownership-1.31.0/lib/code_ownership.rb:112
  sig do
    params(
      backtrace: T.nilable(T::Array[::String])
    ).returns(T::Enumerable[[T.nilable(::CodeTeams::Team), ::String]])
  end
  def backtrace_with_ownership(backtrace); end

  # Given a backtrace from either `Exception#backtrace` or `caller`, find the
  # first owned file in it, useful for figuring out which file is being blamed.
  #
  # source://code_ownership-1.31.0/lib/code_ownership.rb:101
  sig do
    params(
      backtrace: T.nilable(T::Array[::String]),
      excluded_teams: T::Array[::CodeTeams::Team]
    ).returns(T.nilable([::CodeTeams::Team, ::String]))
  end
  def first_owned_file_for_backtrace(backtrace, excluded_teams: T.unsafe(nil)); end

  # Given a backtrace from either `Exception#backtrace` or `caller`, find the
  # first line that corresponds to a file with assigned ownership
  #
  # source://code_ownership-1.31.0/lib/code_ownership.rb:94
  sig do
    params(
      backtrace: T.nilable(T::Array[::String]),
      excluded_teams: T::Array[::CodeTeams::Team]
    ).returns(T.nilable(::CodeTeams::Team))
  end
  def for_backtrace(backtrace, excluded_teams: T.unsafe(nil)); end

  # source://code_ownership-1.31.0/lib/code_ownership.rb:145
  sig { params(klass: T.nilable(T.any(::Class, ::Module))).returns(T.nilable(::CodeTeams::Team)) }
  def for_class(klass); end

  # source://code_ownership-1.31.0/lib/code_ownership.rb:21
  sig { params(file: ::String).returns(T.nilable(::CodeTeams::Team)) }
  def for_file(file); end

  # source://code_ownership-1.31.0/lib/code_ownership.rb:162
  sig { params(package: ::Packs::Pack).returns(T.nilable(::CodeTeams::Team)) }
  def for_package(package); end

  # source://code_ownership-1.31.0/lib/code_ownership.rb:39
  sig { params(team: T.any(::CodeTeams::Team, ::String)).returns(::String) }
  def for_team(team); end

  # source://code_ownership-1.31.0/lib/code_ownership.rb:82
  sig { params(files: T::Array[::String], autocorrect: T::Boolean, stage_changes: T::Boolean).void }
  def validate!(files: T.unsafe(nil), autocorrect: T.unsafe(nil), stage_changes: T.unsafe(nil)); end

  class << self
    # Generally, you should not ever need to do this, because once your ruby process loads, cached content should not change.
    # Namely, the set of files, packages, and directories which are tracked for ownership should not change.
    # The primary reason this is helpful is for clients of CodeOwnership who want to test their code, and each test context
    # has different ownership and tracked files.
    #
    # source://code_ownership-1.31.0/lib/code_ownership.rb:171
    sig { void }
    def bust_caches!; end

    # source://code_ownership-1.31.0/lib/code_ownership.rb:71
    sig { params(filename: ::String).void }
    def remove_file_annotation!(filename); end

    private

    # source://code_ownership-1.31.0/lib/code_ownership.rb:112
    def backtrace_with_ownership(backtrace); end
  end
end

# source://code_ownership-1.31.0/lib/code_ownership/cli.rb:8
class CodeOwnership::Cli
  class << self
    # For now, this just returns team ownership
    # Later, this could also return code ownership errors about that file.
    #
    # source://code_ownership-1.31.0/lib/code_ownership/cli.rb:76
    def for_file(argv); end

    # source://code_ownership-1.31.0/lib/code_ownership/cli.rb:123
    def for_team(argv); end

    # source://code_ownership-1.31.0/lib/code_ownership/cli.rb:9
    def run!(argv); end

    private

    # source://code_ownership-1.31.0/lib/code_ownership/cli.rb:33
    def validate!(argv); end
  end
end

# source://code_ownership-1.31.0/lib/code_ownership.rb:67
class CodeOwnership::InvalidCodeOwnershipConfigurationError < ::StandardError; end

# source://code_ownership-1.31.0/lib/code_ownership/private/configuration.rb:4
module CodeOwnership::Private
  class << self
    # source://code_ownership-1.31.0/lib/code_ownership/private.rb:32
    sig { void }
    def bust_caches!; end

    # source://code_ownership-1.31.0/lib/code_ownership/private.rb:26
    sig { returns(::CodeOwnership::Private::Configuration) }
    def configuration; end

    # source://code_ownership-1.31.0/lib/code_ownership/private.rb:73
    sig { returns(::CodeOwnership::Private::OwnershipMappers::FileAnnotations) }
    def file_annotations_mapper; end

    # source://code_ownership-1.31.0/lib/code_ownership/private.rb:110
    sig { params(files: T::Array[::String]).returns(T::Hash[::String, T::Array[::String]]) }
    def files_by_mapper(files); end

    # source://code_ownership-1.31.0/lib/code_ownership/private.rb:100
    sig { params(team_name: ::String, location_of_reference: ::String).returns(::CodeTeams::Team) }
    def find_team!(team_name, location_of_reference); end

    # source://code_ownership-1.31.0/lib/code_ownership/private.rb:62
    sig { returns(T::Array[::CodeOwnership::Private::OwnershipMappers::Interface]) }
    def mappers; end

    # Returns a string version of the relative path to a Rails constant,
    # or nil if it can't find something
    #
    # source://code_ownership-1.31.0/lib/code_ownership/private.rb:81
    sig { params(klass: T.nilable(T.any(::Class, ::Module))).returns(T.nilable(::String)) }
    def path_from_klass(klass); end

    # The output of this function is string pathnames relative to the root.
    #
    # source://code_ownership-1.31.0/lib/code_ownership/private.rb:94
    sig { returns(T::Array[::String]) }
    def tracked_files; end

    # source://code_ownership-1.31.0/lib/code_ownership/private.rb:39
    sig { params(files: T::Array[::String], autocorrect: T::Boolean, stage_changes: T::Boolean).void }
    def validate!(files:, autocorrect: T.unsafe(nil), stage_changes: T.unsafe(nil)); end
  end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/configuration.rb:5
class CodeOwnership::Private::Configuration < ::T::Struct
  const :js_package_paths, T::Array[::String]
  const :owned_globs, T::Array[::String]
  const :skip_codeowners_validation, T::Boolean
  const :unowned_globs, T::Array[::String]

  class << self
    # source://code_ownership-1.31.0/lib/code_ownership/private/configuration.rb:15
    sig { returns(::CodeOwnership::Private::Configuration) }
    def fetch; end

    # source://sorbet-runtime-0.5.10323/lib/types/struct.rb:13
    def inherited(s); end

    # source://code_ownership-1.31.0/lib/code_ownership/private/configuration.rb:27
    sig { params(config_hash: T::Hash[T.untyped, T.untyped]).returns(T::Array[::String]) }
    def js_package_paths(config_hash); end
  end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/configuration.rb:7
CodeOwnership::Private::Configuration::DEFAULT_JS_PACKAGE_PATHS = T.let(T.unsafe(nil), Array)

# source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/interface.rb:7
module CodeOwnership::Private::OwnershipMappers; end

# Calculate, cache, and return a mapping of file names (relative to the root
# of the repository) to team name.
#
# Example:
#
#   {
#     'app/models/company.rb' => Team.find('Setup & Onboarding'),
#     ...
#   }
#
# source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/file_annotations.rb:17
class CodeOwnership::Private::OwnershipMappers::FileAnnotations
  include ::CodeOwnership::Private::OwnershipMappers::Interface

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/file_annotations.rb:113
  sig { override.void }
  def bust_caches!; end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/file_annotations.rb:102
  sig { override.returns(T::Hash[::String, T.nilable(::CodeTeams::Team)]) }
  def codeowners_lines_to_owners; end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/file_annotations.rb:108
  sig { override.returns(::String) }
  def description; end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/file_annotations.rb:50
  sig { params(filename: ::String).returns(T.nilable(::CodeTeams::Team)) }
  def file_annotation_based_owner(filename); end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/file_annotations.rb:29
  sig { override.params(file: ::String).returns(T.nilable(::CodeTeams::Team)) }
  def map_file_to_owner(file); end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/file_annotations.rb:38
  sig { override.params(files: T::Array[::String]).returns(T::Hash[::String, T.nilable(::CodeTeams::Team)]) }
  def map_files_to_owners(files); end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/file_annotations.rb:86
  sig { params(filename: ::String).void }
  def remove_file_annotation!(filename); end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/file_annotations.rb:23
CodeOwnership::Private::OwnershipMappers::FileAnnotations::TEAM_PATTERN = T.let(T.unsafe(nil), Regexp)

# @abstract Subclasses must implement the `abstract` methods below.
#
# source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/interface.rb:8
module CodeOwnership::Private::OwnershipMappers::Interface
  interface!

  # @abstract
  #
  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/interface.rb:45
  sig { abstract.void }
  def bust_caches!; end

  # @abstract
  #
  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/interface.rb:37
  sig { abstract.returns(T::Hash[::String, T.nilable(::CodeTeams::Team)]) }
  def codeowners_lines_to_owners; end

  # @abstract
  #
  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/interface.rb:41
  sig { abstract.returns(::String) }
  def description; end

  # This should be fast when run with ONE file
  #
  # @abstract
  #
  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/interface.rb:21
  sig { abstract.params(file: ::String).returns(T.nilable(::CodeTeams::Team)) }
  def map_file_to_owner(file); end

  # This should be fast when run with MANY files
  #
  # @abstract
  #
  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/interface.rb:31
  sig { abstract.params(files: T::Array[::String]).returns(T::Hash[::String, T.nilable(::CodeTeams::Team)]) }
  def map_files_to_owners(files); end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/js_package_ownership.rb:8
class CodeOwnership::Private::OwnershipMappers::JsPackageOwnership
  include ::CodeOwnership::Private::OwnershipMappers::Interface

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/js_package_ownership.rb:80
  sig { override.void }
  def bust_caches!; end

  # Package ownership ignores the passed in files when generating code owners lines.
  # This is because Package ownership knows that the fastest way to find code owners for package based ownership
  # is to simply iterate over the packages and grab the owner, rather than iterating over each file just to get what package it is in
  # In theory this means that we may generate code owners lines that cover files that are not in the passed in argument,
  # but in practice this is not of consequence because in reality we never really want to generate code owners for only a
  # subset of files, but rather we want code ownership for all files.
  #
  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/js_package_ownership.rb:54
  sig { override.returns(T::Hash[::String, T.nilable(::CodeTeams::Team)]) }
  def codeowners_lines_to_owners; end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/js_package_ownership.rb:64
  sig { override.returns(::String) }
  def description; end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/js_package_ownership.rb:18
  sig { override.params(file: ::String).returns(T.nilable(::CodeTeams::Team)) }
  def map_file_to_owner(file); end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/js_package_ownership.rb:31
  sig { override.params(files: T::Array[::String]).returns(T::Hash[::String, T.nilable(::CodeTeams::Team)]) }
  def map_files_to_owners(files); end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/js_package_ownership.rb:69
  sig { params(package: ::CodeOwnership::Private::ParseJsPackages::Package).returns(T.nilable(::CodeTeams::Team)) }
  def owner_for_package(package); end

  private

  # takes a file and finds the relevant `package.json` file by walking up the directory
  # structure. Example, given `packages/a/b/c.rb`, this looks for `packages/a/b/package.json`, `packages/a/package.json`,
  # `packages/package.json`, and `package.json` in that order, stopping at the first file to actually exist.
  # We do additional caching so that we don't have to check for file existence every time
  #
  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/js_package_ownership.rb:91
  sig { params(file: ::String).returns(T.nilable(::CodeOwnership::Private::ParseJsPackages::Package)) }
  def map_file_to_relevant_package(file); end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/package_ownership.rb:8
class CodeOwnership::Private::OwnershipMappers::PackageOwnership
  include ::CodeOwnership::Private::OwnershipMappers::Interface

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/package_ownership.rb:80
  sig { override.void }
  def bust_caches!; end

  # Package ownership ignores the passed in files when generating code owners lines.
  # This is because Package ownership knows that the fastest way to find code owners for package based ownership
  # is to simply iterate over the packages and grab the owner, rather than iterating over each file just to get what package it is in
  # In theory this means that we may generate code owners lines that cover files that are not in the passed in argument,
  # but in practice this is not of consequence because in reality we never really want to generate code owners for only a
  # subset of files, but rather we want code ownership for all files.
  #
  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/package_ownership.rb:54
  sig { override.returns(T::Hash[::String, T.nilable(::CodeTeams::Team)]) }
  def codeowners_lines_to_owners; end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/package_ownership.rb:64
  sig { override.returns(::String) }
  def description; end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/package_ownership.rb:18
  sig { override.params(file: ::String).returns(T.nilable(::CodeTeams::Team)) }
  def map_file_to_owner(file); end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/package_ownership.rb:31
  sig { override.params(files: T::Array[::String]).returns(T::Hash[::String, T.nilable(::CodeTeams::Team)]) }
  def map_files_to_owners(files); end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/package_ownership.rb:69
  sig { params(package: ::Packs::Pack).returns(T.nilable(::CodeTeams::Team)) }
  def owner_for_package(package); end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/team_globs.rb:8
class CodeOwnership::Private::OwnershipMappers::TeamGlobs
  include ::CodeOwnership::Private::OwnershipMappers::Interface

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/team_globs.rb:108
  sig { override.void }
  def bust_caches!; end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/team_globs.rb:97
  sig { override.returns(T::Hash[::String, T.nilable(::CodeTeams::Team)]) }
  def codeowners_lines_to_owners; end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/team_globs.rb:114
  sig { override.returns(::String) }
  def description; end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/team_globs.rb:59
  sig { returns(T::Array[::CodeOwnership::Private::OwnershipMappers::TeamGlobs::GlobOverlap]) }
  def find_overlapping_globs; end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/team_globs.rb:90
  sig { override.params(file: ::String).returns(T.nilable(::CodeTeams::Team)) }
  def map_file_to_owner(file); end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/team_globs.rb:22
  sig { override.params(files: T::Array[::String]).returns(T::Hash[::String, T.nilable(::CodeTeams::Team)]) }
  def map_files_to_owners(files); end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/team_globs.rb:39
class CodeOwnership::Private::OwnershipMappers::TeamGlobs::GlobOverlap < ::T::Struct
  const :mapping_contexts, T::Array[::CodeOwnership::Private::OwnershipMappers::TeamGlobs::MappingContext]

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/team_globs.rb:45
  sig { returns(::String) }
  def description; end

  class << self
    # source://sorbet-runtime-0.5.10323/lib/types/struct.rb:13
    def inherited(s); end
  end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/team_globs.rb:34
class CodeOwnership::Private::OwnershipMappers::TeamGlobs::MappingContext < ::T::Struct
  const :glob, ::String
  const :team, ::CodeTeams::Team

  class << self
    # source://sorbet-runtime-0.5.10323/lib/types/struct.rb:13
    def inherited(s); end
  end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/team_yml_ownership.rb:8
class CodeOwnership::Private::OwnershipMappers::TeamYmlOwnership
  include ::CodeOwnership::Private::OwnershipMappers::Interface

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/team_yml_ownership.rb:50
  sig { override.void }
  def bust_caches!; end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/team_yml_ownership.rb:41
  sig { override.returns(T::Hash[::String, T.nilable(::CodeTeams::Team)]) }
  def codeowners_lines_to_owners; end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/team_yml_ownership.rb:56
  sig { override.returns(::String) }
  def description; end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/team_yml_ownership.rb:34
  sig { override.params(file: ::String).returns(T.nilable(::CodeTeams::Team)) }
  def map_file_to_owner(file); end

  # source://code_ownership-1.31.0/lib/code_ownership/private/ownership_mappers/team_yml_ownership.rb:22
  sig { override.params(files: T::Array[::String]).returns(T::Hash[::String, T.nilable(::CodeTeams::Team)]) }
  def map_files_to_owners(files); end
end

# Modeled off of ParsePackwerk
#
# source://code_ownership-1.31.0/lib/code_ownership/private/parse_js_packages.rb:8
module CodeOwnership::Private::ParseJsPackages
  class << self
    # source://code_ownership-1.31.0/lib/code_ownership/private/parse_js_packages.rb:57
    sig { returns(T::Array[::CodeOwnership::Private::ParseJsPackages::Package]) }
    def all; end
  end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/parse_js_packages.rb:13
CodeOwnership::Private::ParseJsPackages::METADATA = T.let(T.unsafe(nil), String)

# source://code_ownership-1.31.0/lib/code_ownership/private/parse_js_packages.rb:12
CodeOwnership::Private::ParseJsPackages::PACKAGE_JSON_NAME = T.let(T.unsafe(nil), String)

# source://code_ownership-1.31.0/lib/code_ownership/private/parse_js_packages.rb:15
class CodeOwnership::Private::ParseJsPackages::Package < ::T::Struct
  const :metadata, T::Hash[::String, T.untyped]
  const :name, ::String

  # source://code_ownership-1.31.0/lib/code_ownership/private/parse_js_packages.rb:48
  sig { returns(::Pathname) }
  def directory; end

  class << self
    # source://code_ownership-1.31.0/lib/code_ownership/private/parse_js_packages.rb:22
    sig { params(pathname: ::Pathname).returns(::CodeOwnership::Private::ParseJsPackages::Package) }
    def from(pathname); end

    # source://sorbet-runtime-0.5.10323/lib/types/struct.rb:13
    def inherited(s); end
  end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/parse_js_packages.rb:11
CodeOwnership::Private::ParseJsPackages::ROOT_PACKAGE_NAME = T.let(T.unsafe(nil), String)

# source://code_ownership-1.31.0/lib/code_ownership/private/team_plugins/ownership.rb:5
module CodeOwnership::Private::TeamPlugins; end

# source://code_ownership-1.31.0/lib/code_ownership/private/team_plugins/github.rb:6
class CodeOwnership::Private::TeamPlugins::Github < ::CodeTeams::Plugin
  # source://code_ownership-1.31.0/lib/code_ownership/private/team_plugins/github.rb:13
  sig { returns(::CodeOwnership::Private::TeamPlugins::Github::GithubStruct) }
  def github; end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/team_plugins/github.rb:10
class CodeOwnership::Private::TeamPlugins::Github::GithubStruct < ::Struct
  # Returns the value of attribute do_not_add_to_codeowners_file
  #
  # @return [Object] the current value of do_not_add_to_codeowners_file
  def do_not_add_to_codeowners_file; end

  # Sets the attribute do_not_add_to_codeowners_file
  #
  # @param value [Object] the value to set the attribute do_not_add_to_codeowners_file to.
  # @return [Object] the newly set value
  def do_not_add_to_codeowners_file=(_); end

  # Returns the value of attribute team
  #
  # @return [Object] the current value of team
  def team; end

  # Sets the attribute team
  #
  # @param value [Object] the value to set the attribute team to.
  # @return [Object] the newly set value
  def team=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/team_plugins/ownership.rb:6
class CodeOwnership::Private::TeamPlugins::Ownership < ::CodeTeams::Plugin
  # source://code_ownership-1.31.0/lib/code_ownership/private/team_plugins/ownership.rb:11
  sig { returns(T::Array[::String]) }
  def owned_globs; end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/validations/interface.rb:5
module CodeOwnership::Private::Validations; end

# source://code_ownership-1.31.0/lib/code_ownership/private/validations/files_have_owners.rb:6
class CodeOwnership::Private::Validations::FilesHaveOwners
  include ::CodeOwnership::Private::Validations::Interface

  # source://code_ownership-1.31.0/lib/code_ownership/private/validations/files_have_owners.rb:12
  sig do
    override
      .params(
        files: T::Array[::String],
        autocorrect: T::Boolean,
        stage_changes: T::Boolean
      ).returns(T::Array[::String])
  end
  def validation_errors(files:, autocorrect: T.unsafe(nil), stage_changes: T.unsafe(nil)); end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/validations/files_have_unique_owners.rb:6
class CodeOwnership::Private::Validations::FilesHaveUniqueOwners
  include ::CodeOwnership::Private::Validations::Interface

  # source://code_ownership-1.31.0/lib/code_ownership/private/validations/files_have_unique_owners.rb:12
  sig do
    override
      .params(
        files: T::Array[::String],
        autocorrect: T::Boolean,
        stage_changes: T::Boolean
      ).returns(T::Array[::String])
  end
  def validation_errors(files:, autocorrect: T.unsafe(nil), stage_changes: T.unsafe(nil)); end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/validations/github_codeowners_up_to_date.rb:6
class CodeOwnership::Private::Validations::GithubCodeownersUpToDate
  include ::CodeOwnership::Private::Validations::Interface

  # source://code_ownership-1.31.0/lib/code_ownership/private/validations/github_codeowners_up_to_date.rb:12
  sig do
    override
      .params(
        files: T::Array[::String],
        autocorrect: T::Boolean,
        stage_changes: T::Boolean
      ).returns(T::Array[::String])
  end
  def validation_errors(files:, autocorrect: T.unsafe(nil), stage_changes: T.unsafe(nil)); end

  private

  # Generate the contents of a CODEOWNERS file that GitHub can use to
  # automatically assign reviewers
  # https://help.github.com/articles/about-codeowners/
  #
  # source://code_ownership-1.31.0/lib/code_ownership/private/validations/github_codeowners_up_to_date.rb:100
  sig { returns(T::Array[::String]) }
  def codeowners_file_lines; end
end

# @abstract Subclasses must implement the `abstract` methods below.
#
# source://code_ownership-1.31.0/lib/code_ownership/private/validations/interface.rb:6
module CodeOwnership::Private::Validations::Interface
  interface!

  # @abstract
  #
  # source://code_ownership-1.31.0/lib/code_ownership/private/validations/interface.rb:13
  sig do
    abstract
      .params(
        files: T::Array[::String],
        autocorrect: T::Boolean,
        stage_changes: T::Boolean
      ).returns(T::Array[::String])
  end
  def validation_errors(files:, autocorrect: T.unsafe(nil), stage_changes: T.unsafe(nil)); end
end

# source://code_ownership-1.31.0/lib/code_ownership/private/validations/no_overlapping_globs.rb:6
class CodeOwnership::Private::Validations::NoOverlappingGlobs
  include ::CodeOwnership::Private::Validations::Interface

  # source://code_ownership-1.31.0/lib/code_ownership/private/validations/no_overlapping_globs.rb:12
  sig do
    override
      .params(
        files: T::Array[::String],
        autocorrect: T::Boolean,
        stage_changes: T::Boolean
      ).returns(T::Array[::String])
  end
  def validation_errors(files:, autocorrect: T.unsafe(nil), stage_changes: T.unsafe(nil)); end
end
