# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `minitest` gem.
# Please instead update this file by running `bin/tapioca gem minitest`.

class Integer < ::Numeric
  include ::JSON::Ext::Generator::GeneratorMethods::Integer
end
