name: CI

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.7
          # See comment comes from https://github.com/ruby/setup-ruby#matrix-of-ruby-versions
          # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
          - '3.0'
          - 3.1
          - head
    env:
      BUNDLE_GEMFILE: Gemfile
    name: "RSpec tests: Ruby ${{ matrix.ruby }}"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Run tests
        run: bundle exec rspec
  visual_regression_suite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.7
          # See comment comes from https://github.com/ruby/setup-ruby#matrix-of-ruby-versions
          # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
          - '3.0'
          - 3.1
          - head
    env:
      BUNDLE_GEMFILE: Gemfile
    name: "Visual Regression Suite: Ruby ${{ matrix.ruby }}"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Run tests
        run: ./spec/ci.sh
  static_type_check:
    name: "Type Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: head
      - name: Run static type checks
        run: bundle exec srb tc
