name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.1
          - 3.2
          - 3.3
    env:
      BUNDLE_GEMFILE: Gemfile
    name: "RSpec tests: Ruby ${{ matrix.ruby }}"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Run tests
        run: bundle exec rspec
  visual_regression_suite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.1
          - 3.2
          - 3.3
    env:
      BUNDLE_GEMFILE: Gemfile
    name: "Visual Regression Suite: Ruby ${{ matrix.ruby }}"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Run tests
        run: ./spec/ci.sh
  static_type_check:
    name: "Type Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: head
      - name: Run static type checks
        run: bundle exec srb tc
